version: "3.9"

services:
    llm_server:
      image: llm_server
      container_name: llm_server
      ports:
        - "50051:50051"
    api_server:
      image: api_server
      ports:
        - "80:8088"
