# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12model_server.proto\"?\n\x0cmodelRequest\x12\x0c\n\x04user\x18\x01 \x01(\x05\x12\x11\n\tmodelName\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\"[\n\rmodelResponse\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x15\n\rexecutionTime\x18\x03 \x01(\x02\x12\x11\n\ttotalTime\x18\x04 \x01(\x02\"\x1e\n\tmodelName\x12\x11\n\tmodelName\x18\x01 \x01(\t\"J\n\x0bmodelConfig\x12\x11\n\tmodelName\x18\x01 \x01(\t\x12\x10\n\x08maxToken\x18\x02 \x01(\x05\x12\x16\n\x0eloadUserRecord\x18\x03 \x01(\x08\"\x1e\n\tmodelInfo\x12\x11\n\tmodelInfo\x18\x01 \x01(\t\" \n\nuserRecord\x12\x12\n\nuserRecord\x18\x01 \x01(\t\"\x1e\n\tqueueSize\x12\x11\n\tqueueSize\x18\x01 \x01(\t\"\"\n\x0b\x63urrentUser\x12\x13\n\x0b\x63urrentUser\x18\x01 \x01(\t\"\x07\n\x05\x65mpty2\xc0\x02\n\nLLMService\x12\x31\n\x10getModelResponse\x12\r.modelRequest\x1a\x0e.modelResponse\x12)\n\x0f\x64\x65leteModelProc\x12\n.modelName\x1a\n.modelInfo\x12+\n\x0f\x63reateModelProc\x12\x0c.modelConfig\x1a\n.modelInfo\x12%\n\x0f\x63heckModelState\x12\x06.empty\x1a\n.modelInfo\x12*\n\x0f\x63heckUSerRecord\x12\n.modelName\x1a\x0b.userRecord\x12\'\n\rshowQueurSize\x12\n.modelName\x1a\n.queueSize\x12+\n\x0fshowCurrentUser\x12\n.modelName\x1a\x0c.currentUserb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MODELREQUEST']._serialized_start=22
  _globals['_MODELREQUEST']._serialized_end=85
  _globals['_MODELRESPONSE']._serialized_start=87
  _globals['_MODELRESPONSE']._serialized_end=178
  _globals['_MODELNAME']._serialized_start=180
  _globals['_MODELNAME']._serialized_end=210
  _globals['_MODELCONFIG']._serialized_start=212
  _globals['_MODELCONFIG']._serialized_end=286
  _globals['_MODELINFO']._serialized_start=288
  _globals['_MODELINFO']._serialized_end=318
  _globals['_USERRECORD']._serialized_start=320
  _globals['_USERRECORD']._serialized_end=352
  _globals['_QUEUESIZE']._serialized_start=354
  _globals['_QUEUESIZE']._serialized_end=384
  _globals['_CURRENTUSER']._serialized_start=386
  _globals['_CURRENTUSER']._serialized_end=420
  _globals['_EMPTY']._serialized_start=422
  _globals['_EMPTY']._serialized_end=429
  _globals['_LLMSERVICE']._serialized_start=432
  _globals['_LLMSERVICE']._serialized_end=752
# @@protoc_insertion_point(module_scope)
